PracticaNetCoreZapatillas/Models/ErrorViewModel.cs
namespace PracticaNetCoreZapatillas.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

PracticaNetCoreZapatillas/Models/Imagen.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace PracticaNetCoreZapatillas.Models
{
	[Table("IMAGENESZAPASPRACTICA")]
	public class Imagen
	{

		[Key]
		[Column("IDIMAGEN")]
		public int IdImagen { get; set; }
		[Column("IDPRODUCTO")]
		public int IdProducto { get; set; }
		[Column("IMAGEN")]
		public string Img { get; set; }
	}
}

PracticaNetCoreZapatillas/Models/ModelPaginacionImagenes.cs
namespace PracticaNetCoreZapatillas.Models
{
	public class ModelPaginacionImagenes
	{
		public Zapatilla Zapatilla { get; set; }

		public int Registros { get; set; }
		public Imagen Imagen { get; set; }
	}
}

PracticaNetCoreZapatillas/Models/Zapatilla.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticaNetCoreZapatillas.Models
{
	[Table("ZAPASPRACTICA")]
	public class Zapatilla
	{
		[Key]
		[Column("IDPRODUCTO")]
		public int IdProducto { get; set; }
		[Column("NOMBRE")]
		public string Nombre { get; set; }
		[Column("DESCRIPCION")]
		public string Descripcion { get; set; }
		[Column("PRECIO")]
		public int Precio { get; set; }
	}
}

PracticaNetCoreZapatillas/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaNetCoreZapatillas.Models;
using System.Diagnostics;

namespace PracticaNetCoreZapatillas.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

PracticaNetCoreZapatillas/Controllers/ZapasController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaNetCoreZapatillas.Models;
using PracticaNetCoreZapatillas.Repositories;

namespace PracticaNetCoreZapatillas.Controllers
{
	public class ZapasController : Controller
	{
		private RepositoryZapas repo;
		
		public ZapasController(RepositoryZapas repo)
		{
			this.repo = repo;
		}

		public async Task<IActionResult> Index()
		{
			List<Zapatilla> zapatillas = await this.repo.GetZapasAsync();
			return View(zapatillas);
		}

		public async Task<IActionResult> ImagenesZapa(int idproducto)
		{
			ModelPaginacionImagenes model = await this.repo.GetImagenesZapa(1, idproducto);
			ViewData["ZAPATILLA"] = model.Zapatilla;
			return View();
		}

		public async Task<IActionResult> _PartialPaginacionImagenes(int? posicion, int idproducto)
		{
			if(posicion == null)
			{
				posicion = 1;
			}
			ModelPaginacionImagenes model = await this.repo.GetImagenesZapa(posicion.Value, idproducto);
			int numRegistros = model.Registros;
			int siguiente = posicion.Value + 1;
			if (siguiente > numRegistros)
			{
				siguiente = numRegistros;
			}
			int anterior = posicion.Value - 1;
			if (anterior < 1)
			{
				anterior = 1;
			}
			ViewData["SIGUIENTE"] = siguiente;
			ViewData["ANTERIOR"] = anterior;
			ViewData["ULTIMO"] = model.Registros;
			ViewData["ZAPATILLA"] = model.Zapatilla;
			ViewData["POSICION"] = posicion;
			return PartialView("_PartialPaginacionImagenes", model.Imagen);

		}

		public async Task<IActionResult> InsertarImagenes()
		{
			List<Zapatilla> zapatillas = await this.repo.GetZapasAsync();
			return View(zapatillas);
		}

		[HttpPost]
		public async Task<IActionResult> InsertarImagenes(List<string> imagenes, int idproducto)
		{
			await this.repo.CreateImagenAsync(imagenes, idproducto);
			return RedirectToAction("ImagenesZapa", new {idproducto = idproducto});
		}
	}
}

PracticaNetCoreZapatillas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PracticaNetCoreZapatillas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaNetCoreZapatillas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticaNetCoreZapatillas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticaNetCoreZapatillas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zapas" asp-action="Index">ZAPATILLAS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zapas" asp-action="InsertarImagenes">Nuevas Imagenes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PracticaNetCoreZapatillas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PracticaNetCoreZapatillas/Views/Zapas/ImagenesZapa.cshtml
@model Imagen

@{
	Zapatilla zapa = ViewData["ZAPATILLA"] as Zapatilla;
}

<h1>Nombre: @zapa.Nombre</h1>
<p>@zapa.Descripcion</p>
<h4>Precio: @zapa.Precio€</h4>


@* <ul class="list-group">
<li class="list-group-item list-group-item-danger">
Id Departamento: @departamento.IdDepartamento
</li>
<li class="list-group-item list-group-item-info">
Nombre: @departamento.Nombre
</li>
<li class="list-group-item list-group-item-info">
Localidad: @departamento.Localidad
</li>
</ul> *@

<div id="visualizarImagen"></div>

<p>
	<a asp-controller="Zapas"
	   asp-action="Index">
		Volver a Index
	</a>
</p>

@section Scripts {
	<script>
		function loadImgPaginacion(posicion){
			$(function() {
				$("#visualizarImagen").load
					("/Zapas/_PartialPaginacionImagenes?posicion=" + posicion + "&idproducto=" + @zapa.IdProducto);
			})
		}
		loadImgPaginacion(1);
	</script>
}

PracticaNetCoreZapatillas/Views/Zapas/Index.cshtml
@model List<Zapatilla>

<h1>Practica ZAPATILLAS</h1>

<ul class="list-group">
	@foreach (Zapatilla zapa in Model)
	{
		<li class="list-group-item">
			<a class="btn btn-dark" asp-controller="Zapas"
			   asp-action="ImagenesZapa"
			   asp-route-idproducto="@zapa.IdProducto">
				@zapa.Nombre
			</a>
		</li>
	}
</ul>

PracticaNetCoreZapatillas/Views/Zapas/InsertarImagenes.cshtml
@model List<Zapatilla>
<h1>Insertar Imagenes</h1>

<button class="btn btn-danger" id="btnNuevaImagenCaja">
    Insertar Nueva Caja IMG
</button>

<div style="width: 650px;margin: 0 auto;padding:10px; border-spacing: 10px">
    <form method="post" id="form1" class="border border-primary" style="padding: 10px">
        <fieldset>
            <legend>Formulario</legend>
            <button class="btn btn-primary">
                Insertar imágenes POST
            </button>
        </fieldset>

        <br>
        <div class="mb-3">
            <label>Seleccione una zapatilla</label>
            <select name="idproducto" class="form-select">
                @foreach (Zapatilla zapa in Model)
                {
                    <option value="@zapa.IdProducto">@zapa.Nombre</option>
                }
            </select>
        </div>
        <div id="contenedorInputs">
            <input type="text" name="imagenes" class="form-control">
        </div>
    </form>
</div>

@section Scripts{
    <script>
        $(function(){
            $("#btnNuevaImagenCaja").click(function(){
                let container = $("#contenedorInputs");
                let cajaNueva = $("<input>", {
                    "type": "text",
                    "name": "imagenes",
                    "class": "form-control"
                });
                container.append(cajaNueva);
            })
        })
    </script>
}

PracticaNetCoreZapatillas/Views/Zapas/_PartialPaginacionImagenes.cshtml
@model Imagen

<div class="card">
	<div class="card-body">
		<h6 style="color:blue">
			Imagen @ViewData["POSICION"] de @ViewData["ULTIMO"]
		</h6>
		<button onclick="loadImgPaginacion(1)" class="btn btn-outline-success">PRIMERO</button>
		<button onclick="loadImgPaginacion(@ViewData["ANTERIOR"])" class="btn btn-outline-success">ANTERIOR</button>
		<button onclick="loadImgPaginacion(@ViewData["SIGUIENTE"])" class="btn btn-outline-success">SIGUIENTE</button>
		<button onclick="loadImgPaginacion(@ViewData["ULTIMO"])" class="btn btn-outline-success">ULTIMO</button>
		<div>
			<img src="@Model.Img" style="100px" />
		</div>
</div>